### ISSUE TITLE
Expose supported api extensions

### ISSUE THREAD

**Issue by geospatial-jeff** [radiantearth/stac-api-spec#30] opened 2020-06-20 19:43 UTC
STAC Items and Collections have the `stac_extensions` field which tells the client what extensions are supported.  This is missing from the API spec which makes it difficult to programmatically determine which extensions are supported by a particular API implementation.  This is particularly important for clients who are interacting with multiple API implementations which don't necessarily use the same STAC extensions.

I think it would make sense to add an optional `stac_api_extensions` field to either the landing page or capabilities document which links to the extensions used by the API.

**Comment by m-mohr** [comment] 2020-06-21 11:09
Duplicate of #27

**Comment by jisantuc** [comment] 2020-06-21 15:21
If we're calling this a duplicate, #27 should be retitled to include the `stac_*` fields intent -- I don't think it's obvious what that issue contains, which makes detecting overlap when opening new issues hard

**Comment by m-mohr** [comment] 2020-06-21 22:12
Good call, I renamed #27.

**Closed by m-mohr** 2020-06-21 22:12 UTC
